fn main() {
    #[cfg(target_os = "windows")]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_manifest_file("app.manifest");
        if let Err(e) = res.compile() {
            eprintln!("Warning: Failed to compile Windows resource: {}", e);
        }
    }

    generate_embed_manifest();
}

/// 扫描 embed/clamav/ 目录，为其中每个文件生成 include_bytes! 条目。
/// 构建时将 ClamAV 二进制文件放入 gui/embed/clamav/ 即可打包为单一 exe。
fn generate_embed_manifest() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let manifest_path = std::path::Path::new(&out_dir).join("embed_manifest.rs");

    let embed_dir = std::path::Path::new("embed").join("clamav");
    println!("cargo:rerun-if-changed=embed/");

    let mut entries: Vec<(String, String)> = Vec::new();

    if embed_dir.exists() && embed_dir.is_dir() {
        collect_embed_files(&embed_dir, &embed_dir, &mut entries);
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — embedded ClamAV binaries\n");
    code.push_str("// Place ClamAV binaries in gui/embed/clamav/ and rebuild\n\n");

    if entries.is_empty() {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const EMBEDDED_FILES: &[(&str, &[u8])] = &[];\n");
    } else {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const EMBEDDED_FILES: &[(&str, &[u8])] = &[\n");
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        for (filename, abs_path) in &entries {
            code.push_str(&format!(
                "    (\"{}\", include_bytes!(\"{}\")),\n",
                filename, abs_path
            ));
        }
        code.push_str("];\n");
    }

    std::fs::write(&manifest_path, code).expect("Failed to write embed manifest");
}

/// 递归收集 embed 目录中的所有文件，保留相对路径
fn collect_embed_files(
    base: &std::path::Path,
    dir: &std::path::Path,
    entries: &mut Vec<(String, String)>,
) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for entry in rd.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            collect_embed_files(base, &path, entries);
        } else if path.is_file() {
            let ext = path
                .extension()
                .map(|e| e.to_string_lossy().to_lowercase())
                .unwrap_or_default();
            if ext == "md" || ext == "txt" {
                continue;
            }
            // 保留相对于 base 的路径（如 "database/main.cvd"）
            if let Ok(rel) = path.strip_prefix(base) {
                let rel_str = rel.to_string_lossy().replace('\\', "/");
                if let Ok(abs_path) = std::fs::canonicalize(&path) {
                    let abs_str = abs_path.to_string_lossy().to_string();
                    let abs_str = if abs_str.starts_with(r"\\?\") {
                        abs_str[4..].to_string()
                    } else {
                        abs_str
                    };
                    let abs_str = abs_str.replace('\\', "/");
                    entries.push((rel_str, abs_str));
                }
            }
        }
    }
}
