fn main() {
    #[cfg(target_os = "windows")]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_manifest_file("app.manifest");
        if let Err(e) = res.compile() {
            eprintln!("Warning: Failed to compile Windows resource: {}", e);
        }
    }

    generate_embed_manifest();
}

/// 扫描 embed/clamav/ 目录，为其中每个文件生成 include_bytes! 条目。
/// 构建时将 ClamAV 二进制文件放入 gui/embed/clamav/ 即可打包为单一 exe。
fn generate_embed_manifest() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let manifest_path = std::path::Path::new(&out_dir).join("embed_manifest.rs");

    let embed_dir = std::path::Path::new("embed").join("clamav");
    println!("cargo:rerun-if-changed=embed/");

    let mut entries: Vec<(String, String)> = Vec::new();

    if embed_dir.exists() && embed_dir.is_dir() {
        if let Ok(dir) = std::fs::read_dir(&embed_dir) {
            for entry in dir.filter_map(|e| e.ok()) {
                let path = entry.path();
                if path.is_file() {
                    // 跳过 README 等非二进制文件
                    let ext = path
                        .extension()
                        .map(|e| e.to_string_lossy().to_lowercase())
                        .unwrap_or_default();
                    if ext == "md" || ext == "txt" {
                        continue;
                    }
                    if let Some(filename) = path.file_name() {
                        let filename = filename.to_string_lossy().to_string();
                        if let Ok(abs_path) = std::fs::canonicalize(&path) {
                            let abs_str = abs_path.to_string_lossy().to_string();
                            // 移除 Windows canonicalize 添加的 \\?\ UNC 前缀
                            let abs_str = if abs_str.starts_with(r"\\?\") {
                                abs_str[4..].to_string()
                            } else {
                                abs_str
                            };
                            let abs_str = abs_str.replace('\\', "/");
                            entries.push((filename, abs_str));
                        }
                    }
                }
            }
        }
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — embedded ClamAV binaries\n");
    code.push_str("// Place ClamAV binaries in gui/embed/clamav/ and rebuild\n\n");

    if entries.is_empty() {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const EMBEDDED_FILES: &[(&str, &[u8])] = &[];\n");
    } else {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const EMBEDDED_FILES: &[(&str, &[u8])] = &[\n");
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        for (filename, abs_path) in &entries {
            code.push_str(&format!(
                "    (\"{}\", include_bytes!(\"{}\")),\n",
                filename, abs_path
            ));
        }
        code.push_str("];\n");
    }

    std::fs::write(&manifest_path, code).expect("Failed to write embed manifest");
}
