fn main() {
    #[cfg(target_os = "windows")]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_manifest_file("app.manifest");
        if let Err(e) = res.compile() {
            eprintln!("Warning: Failed to compile Windows resource: {}", e);
        }
    }

    generate_embed_manifest();
    generate_yamagoya_manifest();
}

/// 扫描 embed/clamav/ 目录，为其中每个文件生成压缩后的嵌入条目。
/// 构建时将 ClamAV 二进制文件放入 gui/embed/clamav/ 即可打包为单一 exe。
fn generate_embed_manifest() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let manifest_path = std::path::Path::new(&out_dir).join("embed_manifest.rs");
    let compressed_dir = std::path::Path::new(&out_dir).join("compressed_clamav");

    let embed_dir = std::path::Path::new("embed").join("clamav");
    println!("cargo:rerun-if-changed=embed/");

    let mut entries: Vec<(String, String)> = Vec::new();

    if embed_dir.exists() && embed_dir.is_dir() {
        let _ = std::fs::create_dir_all(&compressed_dir);
        collect_and_compress_files(&embed_dir, &embed_dir, &compressed_dir, &mut entries);
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — embedded ClamAV binaries (zstd compressed)\n");
    code.push_str("// Place ClamAV binaries in gui/embed/clamav/ and rebuild\n\n");

    if entries.is_empty() {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const EMBEDDED_FILES: &[(&str, &[u8])] = &[];\n");
    } else {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const EMBEDDED_FILES: &[(&str, &[u8])] = &[\n");
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        for (filename, compressed_path) in &entries {
            code.push_str(&format!(
                "    (\"{}\", include_bytes!(\"{}\")),\n",
                filename, compressed_path
            ));
        }
        code.push_str("];\n");
    }

    std::fs::write(&manifest_path, code).expect("Failed to write embed manifest");
}

/// 扫描 embed/yamagoya/ 目录，为 YAMAGoya 可执行文件和规则生成压缩后的嵌入条目。
fn generate_yamagoya_manifest() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let manifest_path = std::path::Path::new(&out_dir).join("yamagoya_manifest.rs");
    let compressed_dir = std::path::Path::new(&out_dir).join("compressed_yamagoya");

    let embed_dir = std::path::Path::new("embed").join("yamagoya");
    println!("cargo:rerun-if-changed=embed/yamagoya/");

    let mut entries: Vec<(String, String)> = Vec::new();

    if embed_dir.exists() && embed_dir.is_dir() {
        let _ = std::fs::create_dir_all(&compressed_dir);
        collect_and_compress_files(&embed_dir, &embed_dir, &compressed_dir, &mut entries);
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — embedded YAMAGoya binaries (zstd compressed)\n");
    code.push_str("// Place YAMAGoya.exe and rules in gui/embed/yamagoya/ and rebuild\n\n");

    if entries.is_empty() {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const YAMAGOYA_FILES: &[(&str, &[u8])] = &[];\n");
    } else {
        code.push_str("#[allow(dead_code)]\n");
        code.push_str("pub const YAMAGOYA_FILES: &[(&str, &[u8])] = &[\n");
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        for (filename, compressed_path) in &entries {
            code.push_str(&format!(
                "    (\"{}\", include_bytes!(\"{}\")),\n",
                filename, compressed_path
            ));
        }
        code.push_str("];\n");
    }

    std::fs::write(&manifest_path, code).expect("Failed to write yamagoya manifest");
}

/// 递归收集并压缩 embed 目录中的所有文件
fn collect_and_compress_files(
    base: &std::path::Path,
    dir: &std::path::Path,
    compressed_dir: &std::path::Path,
    entries: &mut Vec<(String, String)>,
) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for entry in rd.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            collect_and_compress_files(base, &path, compressed_dir, entries);
        } else if path.is_file() {
            let ext = path
                .extension()
                .map(|e| e.to_string_lossy().to_lowercase())
                .unwrap_or_default();
            if ext == "md" || ext == "txt" {
                continue;
            }
            if let Ok(rel) = path.strip_prefix(base) {
                let rel_str = rel.to_string_lossy().replace('\\', "/");
                // 压缩文件名：将路径分隔符替换为下划线，加 .zst 后缀
                let safe_name = rel_str.replace('/', "_") + ".zst";
                let compressed_path = compressed_dir.join(&safe_name);

                // 读取原始文件并用 zstd 压缩
                if let Ok(raw_data) = std::fs::read(&path) {
                    let compressed = zstd::encode_all(raw_data.as_slice(), 19)
                        .expect("Failed to compress embedded file");
                    std::fs::write(&compressed_path, &compressed)
                        .expect("Failed to write compressed file");

                    let original_kb = raw_data.len() / 1024;
                    let compressed_kb = compressed.len() / 1024;
                    println!(
                        "cargo:warning=Compressed {}: {} KB -> {} KB ({:.0}%)",
                        rel_str,
                        original_kb,
                        compressed_kb,
                        compressed.len() as f64 / raw_data.len().max(1) as f64 * 100.0
                    );

                    if let Ok(abs_path) = std::fs::canonicalize(&compressed_path) {
                        let abs_str = abs_path.to_string_lossy().to_string();
                        let abs_str = if abs_str.starts_with(r"\\?\") {
                            abs_str[4..].to_string()
                        } else {
                            abs_str
                        };
                        let abs_str = abs_str.replace('\\', "/");
                        entries.push((rel_str, abs_str));
                    }
                }
            }
        }
    }
}
